### PR TITLE
Cleaning up frontend

### PR DESCRIPTION
**Pull request by tylershuster**
I started to clean up the front end, without changing the way it works. I walked through the `<Item />` component to get familiar with it and globalized the way that moment.js is localized. Then I reduced the dependency on lodash (only uses 'isEqual' in one place, and that could be removed) using ES2018 syntax. Then I included the linting declarations that Urbit core uses and applied its suggestions to all the JavaScript, leaving only a few items flagged.

### CODE REVIEW

**Comment by ryjm** [comment]
thanks!

mind explaining the difference const / let and the " -> ' changes? just curious why the linter makes those changes.

i think this is ready to merge once the app/* changes (tile.js, index.js, index.css) and the dev stuff (urbitrc) get removed.

**Comment by tylershuster** [comment]
`const` v `let` is an ES2016 change from the deprecated `var`. `const` is for variables that won't change; `let` is for variables that will. `const` isn't actually immutable but it ensures they won't be redeclared. I think there's some lexical scoping subtlety in there too, but it's not something that I've had reason to grok.

Double versus single quotes is mostly an issue of preference, and it's one enforced by the styleguide Urbit uses. In PHP double quotes allow for interpolation but in JS there's no difference except in which characters need escaping inside them. I personally prefer single because it cuts down on the amount of ink on the screen so to speak.

I'll make a new commit with the changes you mentioned later today.

**Comment by tylershuster** [comment]
Alright, how does this look?

**Comment by ryjm** [comment]
Looks good! I'll merge it. 

Do you have an ETH address I can send a planet to?

**Pull request merged**
